[package]
name = "chatroom"
version = "0.1.0"
edition = "2021"

[dependencies]

# actix web
actix-web = "4"
actix-http = "3"
actix-cors = "0.7"
actix-web-httpauth = "0.8"
once_cell = "1.19"
rand_core = { version = "0.6", features = ["std"] }

#jwt
argon2 = "0.5"
jsonwebtoken = { version = "9", features = ["use_pem"] }
serde_urlencoded = "0.7"
fancy-regex = "0.13"

# rbatis
rbs = { version = "4.5" }
rbatis = { version = "4.5" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rbdc-pg = { version = "4.5" }

# logging
log = "0.4"
fast_log = "1.6"

# serialization
serde_json = "1"
derive_more = "0.99"
config = "0.14.0"

# tracing
tracing = "0.1.19"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1.1"
thiserror = "1.0.24"
