on: [ push ]

name: 构建发布包到开发环境
run-name: 🚀${{ gitea.actor }} 构建发布包到开发环境

jobs:

  checkout:
    name: 🚀Checkout代码
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
  build:
    name: 🚀运行cargo check检查代码
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo check

  test:
    name: 🚀运行cargo test跑ut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test

  build:
    name: 🚀运行cargo build构建release包
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build
