on: [ push ]

name: 构建发布包到开发环境
run-name: 🚀${{ gitea.actor }} 构建发布包到开发环境

jobs:

  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀Checkout代码
        uses: actions/checkout@v4
      
      - name: 🚀运行cargo check检查代码
        uses: actions-rust-lang/setup-rust-toolchain@v1
        run: cargo check

      - name: 🚀运行cargo test跑ut
        uses: actions-rust-lang/setup-rust-toolchain@v1
        run: cargo test

      - name: 🚀运行cargo build构建release包
        uses: actions-rust-lang/setup-rust-toolchain@v1
        run: cargo build
