port = 8088
host = "127.0.0.1"

cache = "mem"
sms_cache_send_key_prefix = 'sms=send='
login_fail_retry = 3
login_fail_retry_wait_sec = 30
white_list_api = ["/", "/admin/sys_login", "/admin/captcha"]
trash_recycle_days = 90
datetime_format = "YYYY-MM-DD hh=mm=ss"

[database]
url = "postgres://postgres:123456@localhost:5432/postgres"
pool_size = 32
pool_timeout = 60

[log]
# rolling by LogFileSize use[1KB,1MB,1GB]
# rolling by date use ['hour','minute','day'],
# rolling by Duration use ['1hour','10minute','1day']
dir = "target/logs/"
rolling = "day"
# Log rolling retention options=
# Retain all logs= All
# Retain logs by time (in seconds)= KeepTime(i64)
# Retain logs by version= KeepNum(i64)
keep_type = 120
chan_len = 100000
# Optional log packaging formats= "" (keep as .log), "gzip" (GZip compressed), "zip" (ZIP compressed), "lz4" (LZ4 compressed (very fast))
# The following options need to be enabled=
# Inside the toml file, add to 'fast_log'= fast_log = { version = "1.5", features = ["lz4", "zip", "gzip"]}
# In src/config/log.rs, uncomment the section under fn choose_packer()
# In application.json5, add= pack_compress= "zip"
pack_compress = "zip"
level = "info"

[jwt]
secret = "pFWoIfZ4u33D413S0mRy15u8d7/lCaOfjI0Aq+aqIo/9CmWVuH4TgRQQK+KSvYhjksaNe7aUTP9XqN8oTCqfYw3rmiI1XqDlHgkWjL+z7PcfA4r3098kFn9piSCZzZ/B1Un/dB6G+5AR3fjX7wwP23JKDmtKaXo8sdhral9DQJc="
exp = 1800
refresh_token = 600
encode_key = "MC4CAQAwBQYDK2VwBCIEICZ7VioTOmD7OtCdtKzlE2Mt6Zu1ZgFeMUzQy2czP7Ya"
decode_key = "MCowBQYDK2VwAyEA/e9nUPgeM1Fm5ugzAyewQSOe20NIKCpr6WoTIcE4U/E="

[errors]
-1 = "未知错误"
empty = "缺少参数"
"arg.name_empty" = "权限名字不能为空"
"arg.permission_empty" = "权限不能为空"
access_token_empty = "令牌不能为空"
access_denied = "无权限访问"
account_empty = "账户不能为空"
cannot_disable_admin = "不能禁用超级管理员"
dict_exists = "字典已存在"
permission_exists = "权限已存在"
role_id_empty = "角色id不能为空"
please_send_code = "请发送验证码"
role_user_cannot_empty = "添加角色时用户和角色不能为空"
user_not_exists = "用户不存在"
user_and_name_cannot_empty = "用户名和姓名不能为空"
user_cannot_find = "找不到用户"
account_not_exists = "账号不存在"
account_disabled = "账户被禁用"
password_empty = "密码为空"
password_error = "密码不正确"
vcode_error = "验证码不正确"
req_frequently = "操作过于频繁,请等待{}秒后重试"
id_empty = "id不能为空"

