[database]
url = "postgres://postgres:123456@localhost:5432/postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
db_name = "postgres"
ssl = "false"
pool_size = 32
pool_timeout = 60
